## This configuration was generated by terraform-provider-oci

resource oci_artifacts_container_configuration export_container_configuration {
  compartment_id                      = "ocid1.compartment.oc19..aaaaaaaacceqqlruqbgq3hw3jksmecdmkvefvssmdqsppr5rhws4ow5xkrfq"
  is_repository_created_on_first_push = "true"
}

