## This configuration was generated by terraform-provider-oci

resource oci_dns_view export_oke-vcn-quick-cluster1-9f2c0b8e4_1 {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/jens.erik.myhra@sykehuspartner.no"
    "Oracle-Tags.CreatedOn" = "2026-05-27T14:26:29.604Z"
  }
  display_name = "oke-vcn-quick-cluster1-9f2c0b8e4"
  freeform_tags = {
  }
  #scope = <<Optional value not found in discovery>>
}

resource oci_dns_resolver export_oke-vcn-quick-cluster1-9f2c0b8e4_2 {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/jens.erik.myhra@sykehuspartner.no"
    "Oracle-Tags.CreatedOn" = "2026-05-27T14:26:29.604Z"
  }
  display_name = "oke-vcn-quick-cluster1-9f2c0b8e4"
  freeform_tags = {
  }
  resolver_id = "ocid1.dnsresolver.oc19.eu-frankfurt-2.amaaaaaalgam66yazmsumju2jkxjkljtny53kx3nbrteqiwiiay3k4zrj5jq"
  #scope = <<Optional value not found in discovery>>
}

resource oci_dns_zone export_suba9559fb1d-cluster1-oraclevcn-com {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/jens.erik.myhra@sykehuspartner.no"
    "Oracle-Tags.CreatedOn" = "2026-05-27T14:26:30.577Z"
  }
  dnssec_state = "DISABLED"
  freeform_tags = {
  }
  name            = "suba9559fb1d.cluster1.oraclevcn.com"
  resolution_mode = "STATIC"
  scope           = "PRIVATE"
  view_id         = oci_dns_view.export_oke-vcn-quick-cluster1-9f2c0b8e4_1.id
  zone_type       = "PRIMARY"
}

resource oci_dns_zone export_lbsube25da9ebf-cluster1-oraclevcn-com {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/jens.erik.myhra@sykehuspartner.no"
    "Oracle-Tags.CreatedOn" = "2026-05-27T14:26:30.586Z"
  }
  dnssec_state = "DISABLED"
  freeform_tags = {
  }
  name            = "lbsube25da9ebf.cluster1.oraclevcn.com"
  resolution_mode = "STATIC"
  scope           = "PRIVATE"
  view_id         = oci_dns_view.export_oke-vcn-quick-cluster1-9f2c0b8e4_1.id
  zone_type       = "PRIMARY"
}

resource oci_dns_zone export_sub1dec217c7-cluster1-oraclevcn-com {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/jens.erik.myhra@sykehuspartner.no"
    "Oracle-Tags.CreatedOn" = "2026-05-27T14:26:30.577Z"
  }
  dnssec_state = "DISABLED"
  freeform_tags = {
  }
  name            = "sub1dec217c7.cluster1.oraclevcn.com"
  resolution_mode = "STATIC"
  scope           = "PRIVATE"
  view_id         = oci_dns_view.export_oke-vcn-quick-cluster1-9f2c0b8e4_1.id
  zone_type       = "PRIMARY"
}

resource oci_dns_zone export_0-10-in-addr-arpa {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/jens.erik.myhra@sykehuspartner.no"
    "Oracle-Tags.CreatedOn" = "2026-05-27T14:26:29.604Z"
  }
  dnssec_state = "DISABLED"
  freeform_tags = {
  }
  name            = "0.10.in-addr.arpa"
  resolution_mode = "STATIC"
  scope           = "PRIVATE"
  view_id         = oci_dns_view.export_oke-vcn-quick-cluster1-9f2c0b8e4_1.id
  zone_type       = "PRIMARY"
}

resource oci_dns_rrset export_suba9559fb1d-cluster1-oraclevcn-com_oke--cfs3mbzxrwa--nlirgea6hia--sw6blhgi4za--0-suba9559fb1d-cluster1-oraclevcn-com_A {
  domain = "oke-cfs3mbzxrwa-nlirgea6hia-sw6blhgi4za-0.suba9559fb1d.cluster1.oraclevcn.com"
  items {
    domain = "oke-cfs3mbzxrwa-nlirgea6hia-sw6blhgi4za-0.suba9559fb1d.cluster1.oraclevcn.com"
    rdata  = "10.0.10.49"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_suba9559fb1d-cluster1-oraclevcn-com.id
}

resource oci_dns_rrset export_suba9559fb1d-cluster1-oraclevcn-com_oke--cfs3mbzxrwa--nlirgea6hia--sw6blhgi4za--1-suba9559fb1d-cluster1-oraclevcn-com_A {
  domain = "oke-cfs3mbzxrwa-nlirgea6hia-sw6blhgi4za-1.suba9559fb1d.cluster1.oraclevcn.com"
  items {
    domain = "oke-cfs3mbzxrwa-nlirgea6hia-sw6blhgi4za-1.suba9559fb1d.cluster1.oraclevcn.com"
    rdata  = "10.0.10.147"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_suba9559fb1d-cluster1-oraclevcn-com.id
}

resource oci_dns_rrset export_suba9559fb1d-cluster1-oraclevcn-com_oke--cfs3mbzxrwa--nlirgea6hia--sw6blhgi4za--2-suba9559fb1d-cluster1-oraclevcn-com_A {
  domain = "oke-cfs3mbzxrwa-nlirgea6hia-sw6blhgi4za-2.suba9559fb1d.cluster1.oraclevcn.com"
  items {
    domain = "oke-cfs3mbzxrwa-nlirgea6hia-sw6blhgi4za-2.suba9559fb1d.cluster1.oraclevcn.com"
    rdata  = "10.0.10.164"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_suba9559fb1d-cluster1-oraclevcn-com.id
}

resource oci_dns_rrset export_suba9559fb1d-cluster1-oraclevcn-com_suba9559fb1d-cluster1-oraclevcn-com_NS {
  domain = "suba9559fb1d.cluster1.oraclevcn.com"
  items {
    domain = "suba9559fb1d.cluster1.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com."
    rtype  = "NS"
    ttl    = "86400"
  }
  rtype = "NS"
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_suba9559fb1d-cluster1-oraclevcn-com.id
}

resource oci_dns_rrset export_suba9559fb1d-cluster1-oraclevcn-com_suba9559fb1d-cluster1-oraclevcn-com_SOA {
  domain = "suba9559fb1d.cluster1.oraclevcn.com"
  items {
    domain = "suba9559fb1d.cluster1.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com. hostmaster.oracle.com. 2 3600 3600 3600 10"
    rtype  = "SOA"
    ttl    = "86400"
  }
  rtype = "SOA"
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_suba9559fb1d-cluster1-oraclevcn-com.id
}

resource oci_dns_rrset export_lbsube25da9ebf-cluster1-oraclevcn-com_lbsube25da9ebf-cluster1-oraclevcn-com_NS {
  domain = "lbsube25da9ebf.cluster1.oraclevcn.com"
  items {
    domain = "lbsube25da9ebf.cluster1.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com."
    rtype  = "NS"
    ttl    = "86400"
  }
  rtype = "NS"
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_lbsube25da9ebf-cluster1-oraclevcn-com.id
}

resource oci_dns_rrset export_lbsube25da9ebf-cluster1-oraclevcn-com_lbsube25da9ebf-cluster1-oraclevcn-com_SOA {
  domain = "lbsube25da9ebf.cluster1.oraclevcn.com"
  items {
    domain = "lbsube25da9ebf.cluster1.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com. hostmaster.oracle.com. 1 3600 3600 3600 10"
    rtype  = "SOA"
    ttl    = "86400"
  }
  rtype = "SOA"
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_lbsube25da9ebf-cluster1-oraclevcn-com.id
}

resource oci_dns_rrset export_sub1dec217c7-cluster1-oraclevcn-com_cfs3mbzxrwa-sub1dec217c7-cluster1-oraclevcn-com_A {
  domain = "cfs3mbzxrwa.sub1dec217c7.cluster1.oraclevcn.com"
  items {
    domain = "cfs3mbzxrwa.sub1dec217c7.cluster1.oraclevcn.com"
    rdata  = "10.0.0.13"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_sub1dec217c7-cluster1-oraclevcn-com.id
}

resource oci_dns_rrset export_sub1dec217c7-cluster1-oraclevcn-com_sub1dec217c7-cluster1-oraclevcn-com_NS {
  domain = "sub1dec217c7.cluster1.oraclevcn.com"
  items {
    domain = "sub1dec217c7.cluster1.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com."
    rtype  = "NS"
    ttl    = "86400"
  }
  rtype = "NS"
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_sub1dec217c7-cluster1-oraclevcn-com.id
}

resource oci_dns_rrset export_sub1dec217c7-cluster1-oraclevcn-com_sub1dec217c7-cluster1-oraclevcn-com_SOA {
  domain = "sub1dec217c7.cluster1.oraclevcn.com"
  items {
    domain = "sub1dec217c7.cluster1.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com. hostmaster.oracle.com. 2 3600 3600 3600 10"
    rtype  = "SOA"
    ttl    = "86400"
  }
  rtype = "SOA"
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_sub1dec217c7-cluster1-oraclevcn-com.id
}

resource oci_dns_rrset export_0-10-in-addr-arpa_49-10-0-10-in--addr-arpa_PTR {
  domain = "49.10.0.10.in-addr.arpa"
  items {
    domain = "49.10.0.10.in-addr.arpa"
    rdata  = "oke-cfs3mbzxrwa-nlirgea6hia-sw6blhgi4za-0.suba9559fb1d.cluster1.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_0-10-in-addr-arpa.id
}

resource oci_dns_rrset export_0-10-in-addr-arpa_0-10-in--addr-arpa_NS {
  domain = "0.10.in-addr.arpa"
  items {
    domain = "0.10.in-addr.arpa"
    rdata  = "vcn-dns.oraclevcn.com."
    rtype  = "NS"
    ttl    = "86400"
  }
  rtype = "NS"
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_0-10-in-addr-arpa.id
}

resource oci_dns_rrset export_0-10-in-addr-arpa_0-10-in--addr-arpa_SOA {
  domain = "0.10.in-addr.arpa"
  items {
    domain = "0.10.in-addr.arpa"
    rdata  = "vcn-dns.oraclevcn.com. hostmaster.oracle.com. 3 3600 3600 3600 10"
    rtype  = "SOA"
    ttl    = "86400"
  }
  rtype = "SOA"
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_0-10-in-addr-arpa.id
}

resource oci_dns_rrset export_0-10-in-addr-arpa_13-0-0-10-in--addr-arpa_PTR {
  domain = "13.0.0.10.in-addr.arpa"
  items {
    domain = "13.0.0.10.in-addr.arpa"
    rdata  = "cfs3mbzxrwa.sub1dec217c7.cluster1.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_0-10-in-addr-arpa.id
}

resource oci_dns_rrset export_0-10-in-addr-arpa_147-10-0-10-in--addr-arpa_PTR {
  domain = "147.10.0.10.in-addr.arpa"
  items {
    domain = "147.10.0.10.in-addr.arpa"
    rdata  = "oke-cfs3mbzxrwa-nlirgea6hia-sw6blhgi4za-1.suba9559fb1d.cluster1.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_0-10-in-addr-arpa.id
}

resource oci_dns_rrset export_0-10-in-addr-arpa_164-10-0-10-in--addr-arpa_PTR {
  domain = "164.10.0.10.in-addr.arpa"
  items {
    domain = "164.10.0.10.in-addr.arpa"
    rdata  = "oke-cfs3mbzxrwa-nlirgea6hia-sw6blhgi4za-2.suba9559fb1d.cluster1.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_0-10-in-addr-arpa.id
}

