## This configuration was generated by terraform-provider-oci

resource oci_nosql_configuration export_configuration {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  environment    = "MULTI_TENANCY"
  #is_opc_dry_run = <<Optional value not found in discovery>>
  #kms_key = <<Optional value not found in discovery>>
}

