## This configuration was generated by terraform-provider-oci

resource oci_opsi_chargeback_plan export_chargeback_plan {
  compartment_id = "ocid1.tenancy.oc19..aaaaaaaadu4nynpyltw2mbzb7qhmimjldhzpasq5vzffcv7mkw67vy5fnd3a"
  defined_tags = {
  }
  entity_source = "CHARGEBACK_EXADATA"
  freeform_tags = {
  }
  plan_custom_items {
    is_customizable = "false"
    name            = "statistic"
    value           = "AVG"
  }
  plan_custom_items {
    is_customizable = "false"
    name            = "metricCostSplit"
    value           = "CPU:100"
  }
  plan_description = "Equal Allocation Plan"
  plan_name        = "Chargeback Plan - Equal Allocation"
  plan_type        = "EQUAL_ALLOCATION"
}

resource oci_opsi_chargeback_plan export_chargeback_plan_1 {
  compartment_id = "ocid1.tenancy.oc19..aaaaaaaadu4nynpyltw2mbzb7qhmimjldhzpasq5vzffcv7mkw67vy5fnd3a"
  defined_tags = {
  }
  entity_source = "CHARGEBACK_EXADATA"
  freeform_tags = {
  }
  plan_custom_items {
    is_customizable = "false"
    name            = "statistic"
    value           = "AVG"
  }
  plan_custom_items {
    is_customizable = "false"
    name            = "metricCostSplit"
    value           = "CPU:100"
  }
  plan_description = "Weighted Allocation Plan"
  plan_name        = "Chargeback Plan - Weighted Allocation"
  plan_type        = "WEIGHTED_ALLOCATION"
}

resource oci_opsi_chargeback_plan export_chargeback_plan_2 {
  compartment_id = "ocid1.tenancy.oc19..aaaaaaaadu4nynpyltw2mbzb7qhmimjldhzpasq5vzffcv7mkw67vy5fnd3a"
  defined_tags = {
  }
  entity_source = "CHARGEBACK_EXADATA"
  freeform_tags = {
  }
  plan_custom_items {
    is_customizable = "false"
    name            = "statistic"
    value           = "AVG"
  }
  plan_custom_items {
    is_customizable = "false"
    name            = "metricCostSplit"
    value           = "CPU:100"
  }
  plan_description = "Unused Allocation Plan"
  plan_name        = "Chargeback Plan - Unused Allocation"
  plan_type        = "UNUSED_ALLOCATION"
}

