FROM nginx:alpine
COPY index.html /usr/share/nginx/html/index.html
COPY querychat.html /usr/share/nginx/html/chat/index.html
COPY logo.png /usr/share/nginx/html/logo.png
COPY favicon.png /usr/share/nginx/html/favicon.png
COPY logo_emptystate.png /usr/share/nginx/html/logo_emptystate.png