## This configuration was generated by terraform-provider-oci

resource oci_artifacts_container_repository export_rdap-chatbot-container-rep {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
  }
  display_name = "rdap-chatbot-container-rep"
  freeform_tags = {
  }
  is_immutable = "false"
  is_public    = "true"
  readme {
    content = "Readme content"
    format  = " text/markdown"
  }
}

resource oci_artifacts_container_configuration export_container_configuration {
  compartment_id                      = "ocid1.compartment.oc19..aaaaaaaaw7nfek7szdgjrdidzqhkjzx7bw4txy2y3kdydjryavxmei52t5xq"
  is_repository_created_on_first_push = "true"
}

