## This configuration was generated by terraform-provider-oci

resource oci_bastion_bastion export_rdapchatbotbastion {
  bastion_type = "STANDARD"
  client_cidr_block_allow_list = [
    "10.0.4.0/24",
  ]
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/jens.erik.myhra@sykehuspartner.no"
    "Oracle-Tags.CreatedOn" = "2026-06-02T10:23:48.406Z"
  }
  dns_proxy_status = "DISABLED"
  freeform_tags = {
  }
  max_session_ttl_in_seconds = "10800"
  name                       = "rdapchatbotbastion"
  #phone_book_entry = <<Optional value not found in discovery>>
  security_attributes = {
  }
  static_jump_host_ip_addresses = [
  ]
  target_subnet_id = oci_core_subnet.export_bastion-subnet.id
}

