## This configuration was generated by terraform-provider-oci

resource oci_dns_view export_rdap-chatbot-vcn_1 {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/jens.erik.myhra@sykehuspartner.no"
    "Oracle-Tags.CreatedOn" = "2026-05-26T08:06:03.236Z"
  }
  display_name = "rdap-chatbot-vcn"
  freeform_tags = {
    "Department" = "Finance"
  }
  #scope = <<Optional value not found in discovery>>
}

resource oci_dns_resolver export_rdap-chatbot-vcn_2 {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/jens.erik.myhra@sykehuspartner.no"
    "Oracle-Tags.CreatedOn" = "2026-05-26T08:06:03.236Z"
  }
  display_name = "rdap-chatbot-vcn"
  freeform_tags = {
    "Department" = "Finance"
  }
  resolver_id = "ocid1.dnsresolver.oc19.eu-frankfurt-2.amaaaaaalgam66yacdvd4f2kqfvrxtbnmqmosga7es3olpixfebzxerpauxa"
  #scope = <<Optional value not found in discovery>>
}

resource oci_dns_zone export_workernodes-rdapchatbotvcn-oraclevcn-com {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/jens.erik.myhra@sykehuspartner.no"
    "Oracle-Tags.CreatedOn" = "2026-05-26T08:06:04.182Z"
  }
  dnssec_state = "DISABLED"
  freeform_tags = {
  }
  name            = "workernodes.rdapchatbotvcn.oraclevcn.com"
  resolution_mode = "STATIC"
  scope           = "PRIVATE"
  view_id         = oci_dns_view.export_rdap-chatbot-vcn_1.id
  zone_type       = "PRIMARY"
}

resource oci_dns_zone export_loadbalancers-rdapchatbotvcn-oraclevcn-com {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/jens.erik.myhra@sykehuspartner.no"
    "Oracle-Tags.CreatedOn" = "2026-05-26T08:06:04.182Z"
  }
  dnssec_state = "DISABLED"
  freeform_tags = {
  }
  name            = "loadbalancers.rdapchatbotvcn.oraclevcn.com"
  resolution_mode = "STATIC"
  scope           = "PRIVATE"
  view_id         = oci_dns_view.export_rdap-chatbot-vcn_1.id
  zone_type       = "PRIMARY"
}

resource oci_dns_zone export_k8sapiendpoint-rdapchatbotvcn-oraclevcn-com {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/jens.erik.myhra@sykehuspartner.no"
    "Oracle-Tags.CreatedOn" = "2026-05-26T08:06:03.841Z"
  }
  dnssec_state = "DISABLED"
  freeform_tags = {
  }
  name            = "k8sapiendpoint.rdapchatbotvcn.oraclevcn.com"
  resolution_mode = "STATIC"
  scope           = "PRIVATE"
  view_id         = oci_dns_view.export_rdap-chatbot-vcn_1.id
  zone_type       = "PRIMARY"
}

resource oci_dns_zone export_bastion-rdapchatbotvcn-oraclevcn-com {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/jens.erik.myhra@sykehuspartner.no"
    "Oracle-Tags.CreatedOn" = "2026-05-26T08:06:03.841Z"
  }
  dnssec_state = "DISABLED"
  freeform_tags = {
  }
  name            = "bastion.rdapchatbotvcn.oraclevcn.com"
  resolution_mode = "STATIC"
  scope           = "PRIVATE"
  view_id         = oci_dns_view.export_rdap-chatbot-vcn_1.id
  zone_type       = "PRIMARY"
}

resource oci_dns_zone export_0-10-in-addr-arpa {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/jens.erik.myhra@sykehuspartner.no"
    "Oracle-Tags.CreatedOn" = "2026-05-26T08:06:03.236Z"
  }
  dnssec_state = "DISABLED"
  freeform_tags = {
    "Department" = "Finance"
  }
  name            = "0.10.in-addr.arpa"
  resolution_mode = "STATIC"
  scope           = "PRIVATE"
  view_id         = oci_dns_view.export_rdap-chatbot-vcn_1.id
  zone_type       = "PRIMARY"
}

resource oci_dns_rrset export_workernodes-rdapchatbotvcn-oraclevcn-com_oke--cz6qcjcr2pa--n4hhutserzq--sbg3pqfmi6a--0-workernodes-rdapchatbotvcn-oraclevcn-com_A {
  domain = "oke-cz6qcjcr2pa-n4hhutserzq-sbg3pqfmi6a-0.workernodes.rdapchatbotvcn.oraclevcn.com"
  items {
    domain = "oke-cz6qcjcr2pa-n4hhutserzq-sbg3pqfmi6a-0.workernodes.rdapchatbotvcn.oraclevcn.com"
    rdata  = "10.0.1.91"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_workernodes-rdapchatbotvcn-oraclevcn-com.id
}

resource oci_dns_rrset export_workernodes-rdapchatbotvcn-oraclevcn-com_oke--cz6qcjcr2pa--n4hhutserzq--sbg3pqfmi6a--1-workernodes-rdapchatbotvcn-oraclevcn-com_A {
  domain = "oke-cz6qcjcr2pa-n4hhutserzq-sbg3pqfmi6a-1.workernodes.rdapchatbotvcn.oraclevcn.com"
  items {
    domain = "oke-cz6qcjcr2pa-n4hhutserzq-sbg3pqfmi6a-1.workernodes.rdapchatbotvcn.oraclevcn.com"
    rdata  = "10.0.1.128"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_workernodes-rdapchatbotvcn-oraclevcn-com.id
}

resource oci_dns_rrset export_workernodes-rdapchatbotvcn-oraclevcn-com_workernodes-rdapchatbotvcn-oraclevcn-com_NS {
  domain = "workernodes.rdapchatbotvcn.oraclevcn.com"
  items {
    domain = "workernodes.rdapchatbotvcn.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com."
    rtype  = "NS"
    ttl    = "86400"
  }
  rtype = "NS"
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_workernodes-rdapchatbotvcn-oraclevcn-com.id
}

resource oci_dns_rrset export_workernodes-rdapchatbotvcn-oraclevcn-com_workernodes-rdapchatbotvcn-oraclevcn-com_SOA {
  domain = "workernodes.rdapchatbotvcn.oraclevcn.com"
  items {
    domain = "workernodes.rdapchatbotvcn.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com. hostmaster.oracle.com. 4 3600 3600 3600 10"
    rtype  = "SOA"
    ttl    = "86400"
  }
  rtype = "SOA"
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_workernodes-rdapchatbotvcn-oraclevcn-com.id
}

resource oci_dns_rrset export_loadbalancers-rdapchatbotvcn-oraclevcn-com_loadbalancers-rdapchatbotvcn-oraclevcn-com_NS {
  domain = "loadbalancers.rdapchatbotvcn.oraclevcn.com"
  items {
    domain = "loadbalancers.rdapchatbotvcn.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com."
    rtype  = "NS"
    ttl    = "86400"
  }
  rtype = "NS"
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_loadbalancers-rdapchatbotvcn-oraclevcn-com.id
}

resource oci_dns_rrset export_loadbalancers-rdapchatbotvcn-oraclevcn-com_loadbalancers-rdapchatbotvcn-oraclevcn-com_SOA {
  domain = "loadbalancers.rdapchatbotvcn.oraclevcn.com"
  items {
    domain = "loadbalancers.rdapchatbotvcn.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com. hostmaster.oracle.com. 1 3600 3600 3600 10"
    rtype  = "SOA"
    ttl    = "86400"
  }
  rtype = "SOA"
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_loadbalancers-rdapchatbotvcn-oraclevcn-com.id
}

resource oci_dns_rrset export_k8sapiendpoint-rdapchatbotvcn-oraclevcn-com_cz6qcjcr2pa-k8sapiendpoint-rdapchatbotvcn-oraclevcn-com_A {
  domain = "cz6qcjcr2pa.k8sapiendpoint.rdapchatbotvcn.oraclevcn.com"
  items {
    domain = "cz6qcjcr2pa.k8sapiendpoint.rdapchatbotvcn.oraclevcn.com"
    rdata  = "10.0.0.2"
    rtype  = "A"
    ttl    = "300"
  }
  rtype = "A"
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_k8sapiendpoint-rdapchatbotvcn-oraclevcn-com.id
}

resource oci_dns_rrset export_k8sapiendpoint-rdapchatbotvcn-oraclevcn-com_k8sapiendpoint-rdapchatbotvcn-oraclevcn-com_NS {
  domain = "k8sapiendpoint.rdapchatbotvcn.oraclevcn.com"
  items {
    domain = "k8sapiendpoint.rdapchatbotvcn.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com."
    rtype  = "NS"
    ttl    = "86400"
  }
  rtype = "NS"
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_k8sapiendpoint-rdapchatbotvcn-oraclevcn-com.id
}

resource oci_dns_rrset export_k8sapiendpoint-rdapchatbotvcn-oraclevcn-com_k8sapiendpoint-rdapchatbotvcn-oraclevcn-com_SOA {
  domain = "k8sapiendpoint.rdapchatbotvcn.oraclevcn.com"
  items {
    domain = "k8sapiendpoint.rdapchatbotvcn.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com. hostmaster.oracle.com. 2 3600 3600 3600 10"
    rtype  = "SOA"
    ttl    = "86400"
  }
  rtype = "SOA"
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_k8sapiendpoint-rdapchatbotvcn-oraclevcn-com.id
}

resource oci_dns_rrset export_bastion-rdapchatbotvcn-oraclevcn-com_bastion-rdapchatbotvcn-oraclevcn-com_NS {
  domain = "bastion.rdapchatbotvcn.oraclevcn.com"
  items {
    domain = "bastion.rdapchatbotvcn.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com."
    rtype  = "NS"
    ttl    = "86400"
  }
  rtype = "NS"
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_bastion-rdapchatbotvcn-oraclevcn-com.id
}

resource oci_dns_rrset export_bastion-rdapchatbotvcn-oraclevcn-com_bastion-rdapchatbotvcn-oraclevcn-com_SOA {
  domain = "bastion.rdapchatbotvcn.oraclevcn.com"
  items {
    domain = "bastion.rdapchatbotvcn.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com. hostmaster.oracle.com. 1 3600 3600 3600 10"
    rtype  = "SOA"
    ttl    = "86400"
  }
  rtype = "SOA"
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_bastion-rdapchatbotvcn-oraclevcn-com.id
}

resource oci_dns_rrset export_0-10-in-addr-arpa_0-10-in--addr-arpa_NS {
  domain = "0.10.in-addr.arpa"
  items {
    domain = "0.10.in-addr.arpa"
    rdata  = "vcn-dns.oraclevcn.com."
    rtype  = "NS"
    ttl    = "86400"
  }
  rtype = "NS"
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_0-10-in-addr-arpa.id
}

resource oci_dns_rrset export_0-10-in-addr-arpa_0-10-in--addr-arpa_SOA {
  domain = "0.10.in-addr.arpa"
  items {
    domain = "0.10.in-addr.arpa"
    rdata  = "vcn-dns.oraclevcn.com. hostmaster.oracle.com. 5 3600 3600 3600 10"
    rtype  = "SOA"
    ttl    = "86400"
  }
  rtype = "SOA"
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_0-10-in-addr-arpa.id
}

resource oci_dns_rrset export_0-10-in-addr-arpa_128-1-0-10-in--addr-arpa_PTR {
  domain = "128.1.0.10.in-addr.arpa"
  items {
    domain = "128.1.0.10.in-addr.arpa"
    rdata  = "oke-cz6qcjcr2pa-n4hhutserzq-sbg3pqfmi6a-1.workernodes.rdapchatbotvcn.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_0-10-in-addr-arpa.id
}

resource oci_dns_rrset export_0-10-in-addr-arpa_2-0-0-10-in--addr-arpa_PTR {
  domain = "2.0.0.10.in-addr.arpa"
  items {
    domain = "2.0.0.10.in-addr.arpa"
    rdata  = "cz6qcjcr2pa.k8sapiendpoint.rdapchatbotvcn.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_0-10-in-addr-arpa.id
}

resource oci_dns_rrset export_0-10-in-addr-arpa_91-1-0-10-in--addr-arpa_PTR {
  domain = "91.1.0.10.in-addr.arpa"
  items {
    domain = "91.1.0.10.in-addr.arpa"
    rdata  = "oke-cz6qcjcr2pa-n4hhutserzq-sbg3pqfmi6a-0.workernodes.rdapchatbotvcn.oraclevcn.com."
    rtype  = "PTR"
    ttl    = "300"
  }
  rtype = "PTR"
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_0-10-in-addr-arpa.id
}

