## This configuration was generated by terraform-provider-oci

resource oci_functions_application export_rdap-chatbot-application {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  config = {
  }
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/jens.erik.myhra@sykehuspartner.no"
    "Oracle-Tags.CreatedOn" = "2026-05-29T11:12:38.989Z"
  }
  display_name = "rdap-chatbot-application"
  freeform_tags = {
  }
  image_policy_config {
    is_policy_enabled = "false"
  }
  logging {
    line_format = "PLAIN_TEXT"
  }
  network_security_group_ids = [
  ]
  security_attributes = {
  }
  shape = "GENERIC_X86"
  subnet_ids = [
    oci_core_subnet.export_functions-subnet.id,
  ]
  syslog_url = ""
  trace_config {
    domain_id  = ""
    is_enabled = "false"
  }
}

