## This configuration was generated by terraform-provider-oci

resource oci_kms_vault export_rdap-chatbot-vault {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/jens.erik.myhra@sykehuspartner.no"
    "Oracle-Tags.CreatedOn" = "2026-05-29T12:47:29.359Z"
  }
  display_name = "rdap-chatbot-vault"
  #external_key_manager_metadata = <<Optional value not found in discovery>>
  freeform_tags = {
  }
  #restore_from_file = <<Optional value not found in discovery>>
  #restore_from_object_store = <<Optional value not found in discovery>>
  #restore_trigger = <<Optional value not found in discovery>>
  #time_of_deletion = <<Optional value not found in discovery>>
  vault_type = "DEFAULT"
}

resource oci_kms_key export_rdap-chatbot-master-encryption-key {
  #auto_key_rotation_details = <<Optional value not found in discovery>>
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/jens.erik.myhra@sykehuspartner.no"
    "Oracle-Tags.CreatedOn" = "2026-05-29T18:59:56.077Z"
  }
  desired_state = "ENABLED"
  display_name  = "rdap-chatbot-master-encryption-key"
  #external_key_reference = <<Optional value not found in discovery>>
  freeform_tags = {
  }
  is_auto_rotation_enabled = "false"
  key_shape {
    algorithm = "AES"
    curve_id  = ""
    length    = "32"
  }
  management_endpoint = "https://onvbtcxbaage6-management.kms.eu-frankfurt-2.oci.oraclecloud.eu"
  protection_mode     = "SOFTWARE"
  #restore_from_file = <<Optional value not found in discovery>>
  #restore_from_object_store = <<Optional value not found in discovery>>
  #restore_trigger = <<Optional value not found in discovery>>
  #time_of_deletion = <<Optional value not found in discovery>>
}

resource oci_kms_key_version export_rdap-chatbot-master-encryption-key_key_version {
  #external_key_version_id = <<Optional value not found in discovery>>
  key_id              = "ocid1.key.oc19.eu-frankfurt-2.onvbtcxbaage6.abzxiljri3k2lgzfqdn7oytv6mrdir7gd6ug6sovvg2opvifoydgrywlku5a"
  management_endpoint = "https://onvbtcxbaage6-management.kms.eu-frankfurt-2.oci.oraclecloud.eu"
  #time_of_deletion = <<Optional value not found in discovery>>
}

