## This configuration was generated by terraform-provider-oci

resource oci_logging_log_group export_rdap-chatbot-application-log-group {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/jens.erik.myhra@sykehuspartner.no"
    "Oracle-Tags.CreatedOn" = "2026-06-02T08:59:34.570Z"
  }
  #description = <<Optional value not found in discovery>>
  display_name = "rdap-chatbot-application-log-group"
  freeform_tags = {
  }
}

resource oci_logging_log export_rdap-chatbot-application_invoke {
  configuration {
    compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
    source {
      category = "invoke"
      parameters = {
      }
      resource    = oci_functions_application.export_rdap-chatbot-application.id
      service     = "functions"
      source_type = "OCISERVICE"
    }
  }
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/jens.erik.myhra@sykehuspartner.no"
    "Oracle-Tags.CreatedOn" = "2026-06-02T08:59:40.643Z"
  }
  display_name = "rdap-chatbot-application_invoke"
  freeform_tags = {
  }
  is_enabled         = "true"
  log_group_id       = oci_logging_log_group.export_rdap-chatbot-application-log-group.id
  log_type           = "SERVICE"
  retention_duration = "30"
}

