## This configuration was generated by terraform-provider-oci

data oci_objectstorage_namespace export_namespace {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
}
resource oci_objectstorage_bucket export_rdap-chatbot-terraform-state {
  access_type    = "NoPublicAccess"
  auto_tiering   = "Disabled"
  bucket_scope   = "NAMESPACE"
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/jens.erik.myhra@sykehuspartner.no"
    "Oracle-Tags.CreatedOn" = "2026-05-24T12:14:12.085Z"
  }
  freeform_tags = {
    "ManagedBy" = "Terraform"
    "Purpose"   = "RDAPChatbotTerraformState"
  }
  #kms_key_id = <<Optional value not found in discovery>>
  metadata = {
  }
  name                  = "rdap-chatbot-terraform-state"
  namespace             = data.oci_objectstorage_namespace.export_namespace.namespace
  object_events_enabled = "false"
  storage_tier          = "Standard"
  versioning            = "Enabled"
}

resource oci_objectstorage_object export_rdap-chatbot-terraform-state_object {
  bucket = "rdap-chatbot-terraform-state"
  #cache_control = <<Optional value not found in discovery>>
  #content = <<Optional value not found in discovery>>
  #content_disposition = <<Optional value not found in discovery>>
  #content_encoding = <<Optional value not found in discovery>>
  #content_language = <<Optional value not found in discovery>>
  content_md5  = "IpBX5OdkYubduoZIPy3DmA=="
  content_type = "application/json"
  #delete_all_object_versions = <<Optional value not found in discovery>>
  metadata = {
  }
  namespace = data.oci_objectstorage_namespace.export_namespace.namespace
  object    = "rdap_chatbot/terraform.tfstate"
  #opc_sse_kms_key_id = <<Optional value not found in discovery>>
  #source = <<Optional value not found in discovery>>
  #source_uri_details = <<Optional value not found in discovery>>
  storage_tier = "Standard"
}

resource oci_objectstorage_object export_rdap-chatbot-terraform-state_object_1 {
  bucket = "rdap-chatbot-terraform-state"
  #cache_control = <<Optional value not found in discovery>>
  #content = <<Optional value not found in discovery>>
  #content_disposition = <<Optional value not found in discovery>>
  #content_encoding = <<Optional value not found in discovery>>
  #content_language = <<Optional value not found in discovery>>
  content_md5  = "mY5Lb5ACrtFZPYitybR1/g=="
  content_type = "application/json"
  #delete_all_object_versions = <<Optional value not found in discovery>>
  metadata = {
  }
  namespace = data.oci_objectstorage_namespace.export_namespace.namespace
  object    = "rdap_chatbot_infra/terraform.tfstate"
  #opc_sse_kms_key_id = <<Optional value not found in discovery>>
  #source = <<Optional value not found in discovery>>
  #source_uri_details = <<Optional value not found in discovery>>
  storage_tier = "Standard"
}

