## This configuration was generated by terraform-provider-oci

resource oci_vault_secret rdap_chatbot_adb_wallet {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/jens.erik.myhra@sykehuspartner.no"
    "Oracle-Tags.CreatedOn" = "2026-05-29T13:17:21.019Z"
  }
  description = "Oracle Wallet for Autonomous Database used by RDAP Chatbot"
  #enable_auto_generation = <<Optional value not found in discovery>>
  freeform_tags = {
  }
  key_id = "ocid1.key.oc19.eu-frankfurt-2.onvbtcxbaage6.abzxiljrylsjzfqr34f26h6v72klz5r25nzpdasq6citjwzsipetnocfnssa"
  metadata = {
  }
  #secret_content = <<Optional value not found in discovery>>
  secret_name = "rdap-chatbot-adb-wallet"
  vault_id    = oci_kms_vault.export_rdap_chatbot_vault.id
}

